site_name: FileManager
theme: material
repo_name: math2001/FileManager
repo_url: https://github.com/math2001/FileManager
site_description: Sublime Text 3 Plugin FileManager's documentation
site_author: math2001

pages:
  - Home: index.md
  - Getting stated: getting-started.md
  - Commands: commands.md
  - References:
    - Auto Completion: references/auto-completion.md
    - Settings: references/settings.md
    - Templates: references/templates.md
    - Type of path: references/type-of-path.md
    - Aliases: references/aliases.md
  - Contributing: contributing.md
  - License: license.md
  - About: about.md

markdown_extensions:
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - admonition
  - codehilite

extra:
  logo: imgs/FileManager-opposite.svg
  palette:
    primary: red
    accent: Deep Orange
  social:
    - type: github
      link: https://github.com/math2001
    - type: twitter
      link: https://twitter.com/_math2001
